apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: todo-app
      name: todo-app
    spec:
      containers:
        - name: todo-app
          image: gcr.io/PROJECT_ID/app:v1.0.1
          imagePullPolicy: Always
          env:
          - name: 'PORT'
            value: '8080'   
          - name: 'DEPLOYER'
            value: 'GKE'       
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: credential-volume
              mountPath: /usr/src/app/credentials
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          requests:
            memory: "128Mi"
      volumes:
        - name: credential-volume
          secret:
            secretName: credential-secret            
